#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ,               sensorI2CCustom9V)
#pragma config(Sensor, S4,     ,               sensorI2CCustom9V)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Medium, openLoop, encoder)
//*!!Code autobmatically generated by 'ROBOTC' configuration wizard               !!*//

#define READ
#include "include/includes.h"

int encodersMarkers[2] = {655, 745};
short markerColors[2] = {-2, -2};

int encodersElements[4] = {0, 125, 250, 385};
short elementsColors[4] = {-2, -2, -2, -2};

void start(){
    stopMove(50);
	setDefaultLine();
    readColors(encodersMarkers, markerColors, 2, &CDSensor3, 0);
    arcEnc(-20, 20, 50, 50, 135);
    changePosGrabberC(50, grabberC.maxUpWithoutShip);
    lineFollowEncoder(50, 60, 60, 260);
    arcEnc(-60, 60, 60, 20, 345);
    stopMove(100);
    arcEnc(20, -20, 80, 20, 155);
    changePosGrabberC(50, grabberC.maxUp);
    smartTurnRight(40, 80, 60);
    lineFollowCross(60, 100, 1);
    lineBase(100, 20);
    smartTurnLeft(40, 80, 60);
    changePosGrabberC(50, grabberC.maxUpWithoutShip);
    setDefaultLineGreyCross();
    lineFollowEncoder(60, 100, 30, 400);
    lineFollowCross(30, 20, 1);
    stopMove(200);
}

void readingElements(){
    arcEnc(20, -20, 60, 20, 50);
    stopMove(150);
    arcAngle(-20, -20, -80, -20, 80);
    arcAngle(-20, -20, -20, -20, 10);
    stopMove(150);
    arcEnc(20, -20, 20, 20, 100);
    stopMove(150);
    readColors(encodersElements, elementsColors, 4, &CDSensor3, 0);
    arcEnc(-20, 20, 60, 20, 360);
    arcEnc(-20, 20, 20, 20, 30);
    stopMove(150);
    arcAngle(40, -11, 60, 20, 85);
    arcAngle(20, -5.5, 20, 20, 5);
    stopMove(150);
    changePosGrabberC(50, grabberC.maxDown);
    lineFollowEncoder(20, 20, 20, 120);
    stopMove(200);
}

void getElements(short firstColor, short secondColor){
    short turnsEncElements[4] = {74, 21, -21, -74};
    short degreesElements[4] = {220, 180, 180, 220};
    bool markersFound[2] = {false, false};
    short nowPosition = 0;
    short indexesNeed[2] = {0, 1};

    for (short i = 0; i < 4; i++){
        if ((firstColor == elementsColors[i]) && (!markersFound[0])){
            markersFound[0] = true;
            indexesNeed[0] = i;
        }
        else if ((secondColor == elementsColors[i]) && (!markersFound[1])){
            markersFound[1] = true;
            indexesNeed[1] = i;
        }
    }
    
    for (short i = 0; i < 2; i++){
        short angle = turnsEncElements[indexesNeed[i]] - nowPosition
        short way = sgn(angle);
        arcEnc(way * 20, way * 20, way * 50, way * 20, fabs(angle))

        changePosGrabberD(50, grabberD.openMin);
        stopMove(150);
        arcEnc(-20, 20, 40, 20, degreesElements[indexesNeed[i]] - 20);
        changePosGrabberD(50, grabberD.close)
        arcEnc(-20, 20, 20, 20, 20);
        stopMove(150);
        arcEnc(20, -20, 40, 20, degreesElements[indexesNeed[i]] - 20);
        arcEnc(20, -20, 20, 20, 20);
        stopMove(150);
        nowPosition = turnsEncElements[indexesNeed[i]];
    }

    changePosGrabberC(100, grabberC.maxUp);
    arcEnc(30 * sgn(nowPosition), 30 * sgn(nowPosition), 80 * sgn(nowPosition), 30 * sgn(nowPosition), fabs(fabs(nowPosition) - angleToEnc(20, 20, 180)));
    stopMove(200);
}

task main(){
    initAll();
    unsigned long varPgmTime = nPgmTime;
    float now = getBatteryVoltage();
    now = getBatteryVoltage();
    if (now < 7.8){
        playSound(soundException);
    }

    start();
    readingElements();
    getElements(7 - markerColors[0], 7 - markerColors[1]);

    eraseDisplay();
    displayCenteredTextLine(2, "%d", nPgmTime - varPgmTime);

    stopMove(20000);
    fileClose(fileHandle);
}
