#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ,               sensorI2CCustom9V)
#pragma config(Sensor, S4,     ,               sensorI2CCustom9V)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Medium, openLoop, encoder)
//*!!Code autobmatically generated by 'ROBOTC' configuration wizard               !!*//

#define READ

int encodersMarkers_forDop[2] = {475, 570};

int encodersMarkers[2] = {645, 735};
short markerColors[2] = {-2, -2};

int encodersElements[4] = {0, 130, 260, 390};
short elementsColors[4] = {-2, -2, -2, -2};
int encodersWelems[2] = {0, 150};
short welemsColors[2] = {0, 0};
short gotElements[4] = {0, 0, 0, 0};


#include "include/includes.h"



void start(){
    stopMove(250);
	setDefaultLine();
    readColors(encodersMarkers, markerColors, 2, &CDSensor3, 0);
    arcEnc(-30, 30, 50, 50, 135);
    changePosGrabberC(50, grabberC.maxUpWithoutShip);
    lineFollowEncoder(50, 55, 55, 300);
    arcEnc(-55, 55, 55, 20, 305);
    stopMove(100);
    arcEnc(25, -25, 80, 20, 165);
    smartTurnRight_enc(40, 80, 60);
    soundColOfElements(markerColors, 2);
    lineFollowCross(100, 100, 1);
    reactiveTurnLeft()
    changePosGrabberC(50, grabberC.maxUpWithoutShip);
    setDefaultLineGreyCross();
    lineFollowEncoder(100, 100, 30, 450);
    lineFollowCross(30, 25, 1);
    stopMove(200);
}

void start_dop(){
    stopMove(250);
	setDefaultLine();
    readColors(encodersMarkers, markerColors, 2, &CDSensor3, 0);
    arcEnc(-30, 30, 50, 50, 135);
    changePosGrabberC(50, grabberC.maxUpWithoutShip);
    lineFollowEncoder(50, 55, 55, 300);
    arcEnc(-55, 55, 55, 20, 305);
    stopMove(200);
    changePosGrabberD(100, grabberD.openMax);
    arcEnc(30, -30, 30, 30, 50);
    changePosGrabberC(50, grabberC.maxDown);
    stopMove(600);
    changePosGrabberD(100, grabberD.close);
    stopMove(300);
    arcEnc(55, -55, 55, 55, 80);
    stopMove(100);
    arcColor_angle(-60, -60, -100, -60, 80, &CDSensor2, 1);
    lineFollowCross(60, 100, 1);
    lineFollowEncoder(100, 100, 100, 600);
    lineFollowCross(100, 40, 1);
    stopMove(250);
    arcEnc(0, -60, -100, -40, 415);
    stopMove(100);
    arcEnc(-40, 40, 100, 60, 200);
    stopMove(200)
    arcEnc(0, -60, -100, -60, 100);
    changePosGrabberD(100, grabberD.openMax);
    stopMove(100);
    changePosGrabberC(50, grabberC.maxUpWithoutShip);
    stopMove(200);
    arcEnc(30, -30, 30, 30, 50);
    arcColor_angle(-60, -60, -60, -60, 80, &CDSensor2, 1);
    lineFollowCross(80, 100, 1);
    reactiveTurnRight();
    changePosGrabberC(50, grabberC.maxUpWithoutShip);
    setDefaultLineGreyCross();
    lineFollowEncoder(100, 100, 30, 450);
    lineFollowCross(30, 25, 1);
    stopMove(200);

}

void start_dop_fast(){
    stopMove(200);
	setDefaultLine();
    readColors(encodersMarkers, markerColors, 2, &CDSensor3, 0);
    arcEnc(-30, 30, 50, 50, 135);
    changePosGrabberC(50, grabberC.maxUpWithoutShip);
    lineFollowEncoder(50, 55, 55, 300);
    arcEnc(-55, 55, 55, 20, 305);
    stopMove(100);
    changePosGrabberD(100, grabberD.openMax);
    arcEnc(30, -30, 30, 30, 50);
    changePosGrabberC(50, grabberC.maxDown);
    stopMove(500);
    changePosGrabberD(100, grabberD.close);
    stopMove(300);
    arcEnc(55, -55, 55, 55, 80);
    stopMove(100);
    arcColor_angle(-60, -60, -100, -60, 80, &CDSensor2, 1);
    lineFollowCross(60, 100, 1);
    lineFollowEncoder(100, 100, 100, 600);
    lineFollowCross(100, 40, 1);
    stopMove(200);
    arcEnc(0, -60, -100, -40, 425);
    stopMove(100);
    arcEnc(-40, 40, 100, 60, 200);
    stopMove(100)
    arcEnc(0, -60, -100, -60, 100);
    changePosGrabberD(100, grabberD.openMax);
    stopMove(100);
    changePosGrabberC(50, grabberC.maxUpWithoutShip);
    stopMove(100);
    arcEnc(30, -30, 30, 30, 50);
    arcColor_angle(-60, -60, -60, -60, 80, &CDSensor2, 1);
    lineFollowCross(80, 100, 1);
    reactiveTurnRight();
    changePosGrabberC(50, grabberC.maxUpWithoutShip);
    setDefaultLineGreyCross();
    lineFollowEncoder(100, 100, 30, 450);
    lineFollowCross(30, 25, 1);
    stopMove(150);

}

void readingElements(){
    arcEnc(25, -25, 60, 25, 65);
    stopMove(150);
    arcAngle(-25, -25, -80, -25, 80);
    arcAngle(-25, -25, -25, -25, 10);
    stopMove(150);
    arcEnc(25, -25, 25, 25, 100);
    stopMove(200);
    readColors(encodersElements, elementsColors, 4, &CDSensor3, 0);
    arcEnc(-25, 25, 60, 25, 365);
    arcEnc(-25, 25, 25, 25, 35);
    stopMove(0);
    soundColOfElements(elementsColors, 4);
    stopMove(150);
    arcAngle(40, -11.2, 60, 30, 85);
    arcAngle(30, -8.4, 30, 30, 5);
    stopMove(200);
    changePosGrabberC(40, grabberC.maxDown);
    lineFollowEncoder(25, 25, 25, 135);
    stopMove(300);
}

void readingElements_fast(){
    arcEnc(25, -25, 60, 25, 65);
    stopMove(200);
    arcAngle(-25, -25, -80, -25, 80);
    arcAngle(-25, -25, -25, -25, 10);
    stopMove(100);
    arcEnc(25, -25, 25, 25, 100);
    stopMove(200);
    readColors(encodersElements, elementsColors, 4, &CDSensor3, 0);
    arcEnc(-25, 25, 60, 25, 365);
    arcEnc(-25, 25, 25, 25, 35);
    stopMove(0);
    soundColOfElements(elementsColors, 4);
    stopMove(200);
    arcAngle(40, -11.2, 60, 30, 85);
    arcAngle(30, -8.4, 30, 30, 5);
    stopMove(200);
    changePosGrabberC(50, grabberC.maxDown);
    lineFollowEncoder(25, 25, 25, 105);
    stopMove(200);
}

void getElements(short firstColor, short secondColor, short finalPos=0, short getLast=0){
    short turnsEncElements[4] = {70, 25, -25, -70};
    short degreesElements[4] = {203, 180, 180, 203};
    bool markersFound[2] = {false, false};
    short nowPosition = 0;
    short indexesNeed[2] = {0, 1};
    if (getLast){
    	for(short i = 0; i < 4; i++){
    		if ((!gotElements[i]) && (!markersFound[0])){
    			indexesNeed[0] = i;
    			gotElements[i] = 1;
    			markersFound[0] = true;
    		}
    		else if ((!gotElements[i]) && (!markersFound[1])){
    			indexesNeed[1] = i;
    			gotElements[i] = 1;
    			markersFound[1] = true;
    		}
    	}
    }
    else{
	    for (short i = 0; i < 4; i++){
	        if ((firstColor == elementsColors[i]) && (!markersFound[0])){
	            markersFound[0] = true;
	            indexesNeed[0] = i;
	        }
	        else if ((secondColor == elementsColors[i]) && (!markersFound[1])){
	            markersFound[1] = true;
	            indexesNeed[1] = i;
	        }
	    }
	}

    gotElements[indexesNeed[0]] = 1;
    gotElements[indexesNeed[1]] = 1;

    for (short i = 0; i < 2; i++){
        short angle = turnsEncElements[indexesNeed[i]] - nowPosition;
        short way = sgn(angle);
        arcEnc(way * 20, way * 20, way * 40, way * 20, fabs(angle));


        stopMove(150);
        arcEnc(-25, 25, 25, 25, 20);
        changePosGrabberD(100, grabberD.openMin);
        stopMove(100);
        arcEnc(-25, 25, 40, 25, degreesElements[indexesNeed[i]] - 60);
        changePosGrabberD(100, grabberD.close);
        arcEnc(-25, 25, 25, 25, 40);
        stopMove(150);
        arcEnc(25, -25, 40, 25, degreesElements[indexesNeed[i]] - 20);
        arcEnc(25, -25, 25, 25, 20);
        stopMove(150);
        nowPosition = turnsEncElements[indexesNeed[i]];
        elementsColors[indexesNeed[i]] = -1;
    }

    if (finalPos == 0) {
        short signPos = sgn(nowPosition);
        short angle = angleToEnc(20, 20, 180) - fabs(nowPosition);
        if (signPos > 0){
            smartTurnLeft_enc(40, 80, 60, fabs(angle));
        }
        else{
            smartTurnRight_enc(40, 80, 60, fabs(angle));
        }
    } else {
        short signPos = sgn(nowPosition);
        short angle = fabs(nowPosition);
        if (signPos > 0) {
            arcEnc(-30, -30, -40, -30, fabs(angle));
        } else {
            arcEnc(30, 30, 40, 30, fabs(angle));
        }
    }
}

void takeSmallShipAndThrowOn() {
    setDefaultLine();
    lineFollowEncoder(70, 70, 70, 50)
    changePosGrabberD(100, grabberD.openMin);
    lineFollowCross(70, 100, 1);
    lineFollowEncoder(100, 100, 100, 50);
    changePosGrabberD(100, grabberD.close);
    lineFollowEncoder(100, 100, 100, 50);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    lineFollowEncoder(100, 100, 100, 95);
    lineFollowCross(100, 20, 1);
    stopMove(150);
    changePosGrabberC(100, grabberC.maxUp);
    stopMove(300);
    arcEnc(60, 60, 100, 60, 400);
    arcColor_enc(-60, 60, 100, 80, 700, &CDSensor2, 1);
    arcEnc(-80, 80, 80, 80, 30);
    arcColor_enc(-80, 0, -100, -100, 40, &CDSensor2, 1);
    lineFollowCross(100, 100, 1);
    lineFollowEncoder(100, 100, 50, 850);
    arcAngle(0, 50, 100, 40, 80);
    changePosGrabberC(100, grabberC.upForDrop);
    arcAngle(0, 40, 40, 40, 10);
    stopMove(50);
    arcEnc(30, -30, 30, 30, 25);
    stopMove(450);
    changePosGrabberD(100, grabberD.openMin);
    stopMove(200);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    stopMove(200);
    arcColor_angle(70, 0, 100, 50, 80, &CDSensor1, 1);
}



void fromSmallShipToElement() {
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    setDefaultLine();
    lineFollowCross(80, 100, 2);
    reactiveTurnRight();
}

void takeTwoLastElems() {
    setDefaultLineGreyCross();
    changePosGrabberD(100, grabberD.openMax);
    changePosGrabberC(60, grabberC.upForDrop);
    lineFollowEncoder(100, 100, 30, 380);
    lineFollowCross(30, 20, 1);
    stopMove(250);
    arcEnc(25, -25, 50, 20, 175);
    arcEnc(20, -20, 20, 20, 30);
    changePosGrabberC(30, grabberC.maxDown);
    stopMove(250);
    getElements(markerColors[0], markerColors[1], 1, 1);
    lineFollowEncoder(30, 30, 30, 10);
    changePosGrabberD(100, grabberD.openMin);
    lineFollowEncoder(30, 30, 30, 50);
    changePosGrabberD(100, grabberD.close);
    lineFollowCross(30, 25, 1);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    stopMove(200);
}

void takeBigShipAndThrowOn() {
    setDefaultLine();
    arcEnc(25, -25, 25, 25, 90);
    stopMove(200);
    arcAngle(30, 30, 100, 30, 80);
    arcAngle(30, 30, 30, 30, 10);
    stopMove(250);
    arcEnc(-40, 40, 100, 25, 615);
    arcEnc(-20, 20, 20, 20, 80);
    stopMove(25);
    changePosGrabberC(100, grabberC.maxUp);
    arcEnc(-25, 25, 25, 25, 60);
    stopMove(50);
    arcEnc(35, 35, 100, 35, 350);
    arcColor_enc(-40, 40, 100, 45, 580, &CDSensor1, 1);
    arcEnc(-45, 45, 45, 45, 50);
    arcColor_enc(0, 45, 100, 70, 600, &CDSensor1, 1);
    lineFollowEncoder(70, 100, 100, 300, 20);
    lineFollowCross(100, 100, 1, 20);
    lineFollowEncoder(100, 100, 100, 950, 20);
    lineFollowCross(100, 40, 1, 20);
    arcAngle(-40, 0, -100, -40, 90);
    lineFollowEncoder(40, 60, 30, 315);

    stopMove(200);
    arcEnc(40, -40, 100, 30, 325);
    changePosGrabberC(100, grabberC.upForDrop);
    stopMove(500);
    arcEnc(30, -30, 30, 30, 25);
    stopMove(50);
    changePosGrabberD(100, grabberD.openMin);
    stopMove(250);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    arcEnc(40, -40, 100, 60, 115);
    smartTurnRight_angle(60, 100, 60);
    stopMove(0);
}

void getLeftWelem(int f=0) {
    arcEnc(0, 30, 40, 30, 60);
    changePosGrabberD(100, grabberD.openMin);
    stopMove(100);
    arcEnc(-30, 30, 40, 30, 150);
    changePosGrabberD(100, grabberD.close);
    stopMove(200);
    arcEnc(30, -30, 40, 30, 150);
    if (f == 1) {
        arcEnc(0, -30, -40, -30, 60);
    }

}

void getRightWelem(int f=0) {
    arcEnc(-30, 0, -40, -30, 60);
    changePosGrabberD(100, grabberD.openMin);
    stopMove(100);
    arcEnc(-30, 30, 40, 30, 150);
    changePosGrabberD(100, grabberD.close);
    stopMove(200);
    arcEnc(30, -30, 40, 30, 150);
    arcEnc(30, 0, 40, 30, 60);
    if (f == 1) {
        arcEnc(0, -30, -40, -30, 60);
    }
}

void takeLastWhiteAndFinish() {
    lineFollowCross(70, 100, 1);
    changePosGrabberD(100, grabberD.openMax);
    reactiveTurnRight();
    setDefaultLineGreyCross();
    lineFollowEncoder(100, 100, 30, 450);
    lineFollowCross(30, 20, 1);

    stopMove(200);
    changePosGrabberC(30, grabberC.maxDown);
    arcEnc(30, -30, 100, 25, 160);
    stopMove(300);
    arcEnc(30, 30, 30, 30, 35);
    changePosGrabberD(100, grabberD.openMin);
    stopMove(200);
    arcEnc(-30, 30, 30, 30, 100);
    changePosGrabberD(100, grabberD.close);
    stopMove(200);
    changePosGrabberC(60, grabberC.maxUpWithoutShip);
    arcEnc(30, -30, 30, 30, 100);
    smartTurnLeft_angle(60, 100, 60, 170);

    // stopMove(200);
    // changePosGrabberC(60, grabberC.maxDown);
    // arcEnc(40, -40, 100, 25, 220);
    // stopMove(300);
    // getLeftWelem();
    // changePosGrabberC(90, grabberC.maxUpWithoutShip);
    // smartTurnLeft_angle(80, 100, 60, 180);

    setDefaultLine();
    lineFollowCross(80, 100, 1);
    reactiveTurnLeft();
    lineFollowCross(100, 100, 1);
    changePosGrabberC(100, grabberC.upForDrop);
    arcEnc(-100, 100, 100, 40, 90);
    arcAngle(-40, 0, -100, -40, 85);
    stopMove(250);
    changePosGrabberD(60, grabberD.openMin);
    stopMove(200);
    changePosGrabberC(100, grabberC.maxUp);
    arcEnc(30, -30, 60, 30, 30);
    arcAngle(50, 0, 100, 50, 68);
    smartTurnLeft_angle(50, 100, 50, 107);
    lineFollowEncoder(50, 50, 50, 340);
    arcEnc(-50, 50, 50, 25, 340);
    stopMove(200);
}




void takeBigShipFromCrossToElements() {
    setDefaultLine();

    lineFollowEncoder(40, 100, 40, 415);
    arcAngle(0, 40, 100, 40, 90);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    arcEnc(-40, 40, 100, 25, 560);
    arcEnc(-25, 25, 25, 25, 80);
    changePosGrabberC(100, grabberC.maxUp);

    arcEnc(-25, 25, 25, 25, 40);
    stopMove(250);
    arcAngle(40, 40, 100, 40, 90);
    stopMove(100);
    arcColor_enc(-40, 40, 100, 40, 400, &CDSensor1, 1);
    arcToBase(40, 40, 40);
    stopMove(200);
    arcAngle(40, 40, 100, 40, 90);
    stopMove(200);
}

void after() {
    setDefaultLine();
    arcAngle(60, 60, 60, 60, 180);
    lineFollowCross(70, 100, 1);
    lineFollowEncoder(100, 100, 100, 300);
    lineFollowCross(100, 40, 1);
    arcAngle(0, 50, 100, 40, 98);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    arcEnc(-40, 40, 100, 25, 420);
    arcEnc(-25, 25, 25, 25, 80);
    stopMove(50);
    changePosGrabberC(100, grabberC.maxUp);
    stopMove(200);
    arcEnc(-55, 55, 55, 55, 300);
    stopMove(100);
    smartTurnLeft_enc(55, 55, 55, 1);
    lineFollowCross(55, 55, 1);
    lineBase(55, 55);
    smartTurnRight_angle(55, 55, 55, 90);


    lineFollowEncoder(55, 100, 100, 600, 20);
    lineFollowCross(100, 40, 1, 20);
    arcColor_angle(-40, 0, -100, -40, 90, &CDSensor2, 1);
    lineFollowEncoder(40, 60, 30, 315);

    stopMove(200);
    arcEnc(40, -40, 100, 30, 325);
    changePosGrabberC(100, grabberC.upForDrop);
    stopMove(500);
    arcEnc(30, -30, 30, 30, 25);
    stopMove(50);
    changePosGrabberD(100, grabberD.openMin);
    stopMove(250);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    arcEnc(40, -40, 100, 60, 115);
    smartTurnRight_angle(60, 100, 60);

}

void after_fast() {
    setDefaultLine();
    arcAngle(60, 60, 100, 60, 180);
    lineFollowCross(70, 100, 1);
    lineFollowEncoder(100, 100, 100, 300);
    lineFollowCross(100, 40, 1);
    arcAngle(0, 50, 100, 40, 97);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    arcEnc(-40, 40, 100, 25, 420);
    arcEnc(-25, 25, 25, 25, 80);
    stopMove(50);
    changePosGrabberC(100, grabberC.maxUp);
    stopMove(200);
    arcEnc(-55, 55, 100, 35, 300);
    stopMove(100);
    smartTurnLeft_enc(55, 100, 45, 1);
    lineFollowCross(45, 55, 1);
    lineBase(55, 55);
    smartTurnRight_angle(55, 100, 45, 90);


    lineFollowEncoder(55, 100, 100, 700, 20);
    lineFollowCross(100, 55, 1, 20);
    arcColor_angle(-55, 0, -100, -55, 90, &CDSensor2, 1);
    lineFollowEncoder(55, 70, 25, 315);

    stopMove(200);
    arcEnc(40, -40, 100, 30, 290);
    changePosGrabberC(100, grabberC.upForDrop);
    stopMove(500);
    arcEnc(30, -30, 30, 30, 25);
    stopMove(50);
    changePosGrabberD(100, grabberD.openMin);
    stopMove(250);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    arcEnc(60, -60, 100, 60, 120);
    smartTurnRight_angle(60, 100, 60);

}

void huy() {
    lineFollowCross(50, 100, 2);
    lineFollowEncoder(100, 100, 100, 600);
    lineFollowCross(100, 40, 1);
    changePosGrabberC(60, grabberC.maxDown);
    arcAngle(-40, 0, -100, -30, 95);
    changePosGrabberD(100, grabberD.openMin);
    arcEnc(-30, 30, 100, 30, 405);
    changePosGrabberD(100, grabberD.close);
    stopMove(200);
    changePosGrabberC(60, grabberC.maxUpWithoutShip);
    arcEnc(30, -30, 100, 30, 405);
    arcAngle(40, 0, 100, 30, 95);
    stopMove(200);
    smartTurnLeft_angle(50, 100, 50, 180);
    lineFollowCross(100, 100, 3);
    changePosGrabberC(100, grabberC.upForDrop);
    arcEnc(-100, 100, 100, 40, 90);
    arcAngle(-40, 0, -100, -40, 88);
    stopMove(250);
    changePosGrabberD(60, grabberD.openMin);
    stopMove(200);
    changePosGrabberC(100, grabberC.maxUp);
    arcEnc(30, -30, 60, 30, 30);
    arcAngle(50, 0, 100, 50, 71);
    smartTurnLeft_angle(50, 100, 50, 107);
    lineFollowEncoder(50, 50, 50, 340);
    arcEnc(-50, 50, 50, 25, 340);
    stopMove(200);
}

void huy_fast() {
    lineFollowCross(80, 100, 2);
    lineFollowEncoder(100, 100, 100, 600);
    lineFollowCross(100, 30, 1);
    changePosGrabberC(60, grabberC.maxDown);
    arcAngle(-40, 0, -100, -30, 95);
    changePosGrabberD(100, grabberD.openMin);
    arcEnc(-30, 30, 100, 30, 405);
    changePosGrabberD(100, grabberD.close);
    stopMove(200);
    changePosGrabberC(60, grabberC.maxUpWithoutShip);
    arcEnc(50, -50, 100, 60, 405);
    arcAngle(60, 0, 100, 50, 95);
    smartTurnLeft_angle(50, 100, 50, 180);
    lineFollowCross(100, 100, 3);
    changePosGrabberC(100, grabberC.upForDrop);
    arcEnc(-100, 100, 100, 40, 90);
    arcAngle(-40, 0, -100, -40, 88);
    stopMove(250);
    changePosGrabberD(60, grabberD.openMin);
    stopMove(200);
    changePosGrabberC(100, grabberC.maxUp);
    arcEnc(50, -50, 50, 50, 30);
    arcAngle(50, 0, 100, 50, 71);
    smartTurnLeft_angle(50, 100, 50, 107);
    lineFollowEncoder(50, 100, 50, 340);
    arcEnc(-50, 50, 50, 25, 340);
    stopMove(200);
}

task main(){
    initAll();
    unsigned long varPgmTime = nPgmTime;
    float now = getBatteryVoltage();
    now = getBatteryVoltage();
    if (now < 7.8){
        playSound(soundException);
    }

    stopMove(500);
    setLeftSensorBlueLineBlackStop(1, 2);
    // toRightWelemBlueLine();
    // stopMove(1298312);
    start();
    readingElements();

    getElements(7 - markerColors[0], 7 - markerColors[1]);

    takeSmallShipAndThrowOn();

    fromSmallShipToElement();

    takeTwoLastElems();

    takeBigShipAndThrowOn();

    takeLastWhiteAndFinish();

    eraseDisplay();
    displayCenteredTextLine(2, "%d", nPgmTime - varPgmTime);

    stopMove(20000);
    fileClose(fileHandle);
}
