#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ,               sensorI2CCustom9V)
#pragma config(Sensor, S4,     ,               sensorI2CCustom9V)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Medium, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define READ
#include "include/includes.h"

short markers[2] = {0, 0};
short elements[4] = {0, 0, 0, 0};
int encoders_markers[2] = {390, 470};
int encoders_elements[4] = {603, 733, 863, 993};

void getCenterThenBorderElements(){
    setDefaultLine();
    lineFollowEncoder(30, 80, 30, 235);
    arcEnc(-30, 30, 30, 20, 25);
    changePosGrabberD(80, grabberD.openForwardMax);
    arcEnc(30, -30, 50, 20, 150);
    stopMove(200);

    arcAngle(30, 30, 70, 20, 20);

    arcEnc(-30, 30, 40, 20, 85);
    changePosGrabberD(80, grabberD.closeBoth);
    stopMove(300);
    arcEnc(30, -30, 40, 20, 165);

    arcAngle(-30, -30, 70, 20, 33.5);

    changePosGrabberD(80, grabberD.openForwardMax);
    arcEnc(-30, 30, 40, 20, 170);
    changePosGrabberD(80, grabberD.closeBoth);
    stopMove(250);
    arcEnc(30, -30, 40, 20, 280);
    stopMove(250);
    changePosGrabberC(80, grabberC.maxUp);
    arcAngle(30, 30, 40, 20, 16);
}

void getBorderThenCenterElements(){
    setDefaultLine();
    arcAngle(40, 0, 100, 40, 40);
    arcEnc(-30, 30, 40, 40, 165);
    arcEnc(-75, 41, 50, 35, 175);
    arcEnc(-35, 35, 35, 20, 50);
    changePosGrabberD(80, grabberD.openForwardMax);
    stopMove(200);

    arcAngle(50, 0, 100, 40, 90);
    arcAngle(0, -50, 100, 40, 112);
    changePosGrabberD(80, grabberD.openBackwardMin);
    stopMove(200);

    arcEnc(-30, 30, 40, 20, 250);
    changePosGrabberD(80, grabberD.openForwardMax);
    stopMove(200);

    arcAngle(0, -30, 100, 40, 76.5);
    arcAngle(30, 0, 100, 40, 76.5);
    stopMove(200);
    lineFollowEncoder(20, 80, 20, 220);
    changePosGrabberD(80, grabberD.closeBoth);
    stopMove(250);
    changePosGrabberC(80, grabberC.maxUp);
}

void getOneByOneFromLeft(){
    setDefaultLine();
    arcEnc(20, -20, 20, 20, 30);
    stopMove(100);
    arcAngle(20, 20, 100, 20, 90);
    stopMove(200);
    arcAngle(-80, 15, 80, 20, 90);
    arcEnc(-20, 20, 20, 20, 60);
    changePosGrabberD(80, grabberD.openForwardMax);
    stopMove(200);
    arcEnc(20, -20, 20, 20, 30);
    stopMove(100);
    arcAngle(80, -15, 80, 20, 90);
    stopMove(100);
    arcEnc(20, -20, 50, 20, 130);
    stopMove(100);
    arcAngle(-20, -20, 100, 20, 90);
    stopMove(100);
    arcEnc(-20, 20, 100, 15, 170);
    changePosGrabberD(80, grabberD.closeBoth);
    stopMove(200);
    arcAngle(0, -90, 80, 50, 90);
    arcEnc(-20, 20, 40, 15, 45);
    stopMove(200);

    arcAngle(25, 25, 80, 25, 90);
    changePosGrabberD(60, grabberD.openBackwardMax);
    stopMove(550);

    setDefaultLine();
    lineFollowEncoder(25, 25, 20, 180);
    changePosGrabberD(60, grabberD.openForwardMin);
    arcEnc(-20, 20, 20, 20, 40);
    stopMove(100);
    arcEnc(20, -20, 20, 20, 40);
    stopMove(100);
    changePosGrabberD(80, grabberD.closeBoth);
    stopMove(550);
    changePosGrabberC(100, grabberC.maxUp);
}

void getOneByOneFromRight(){
    setDefaultLine();
    arcEnc(20, -20, 20, 20, 30);
    arcAngle(-20, -20, 100, 20, 90);
    stopMove(100);
    arcAngle(-14.8, 80, 80, 20, 90);
    arcEnc(-20, 20, 20, 20, 60);
    changePosGrabberD(80, grabberD.openForwardMax);
    stopMove(150);
    arcEnc(20, -20, 20, 20, 30);

    arcAngle(14.8, -80, 80, 20, 90);
    stopMove(100);
    arcEnc(20, -20, 50, 20, 180);
    stopMove(100);
    arcAngle(20, 20, 100, 20, 90);
    stopMove(100);
    arcEnc(-20, 20, 50, 20, 170);
    changePosGrabberD(80, grabberD.closeBoth);
    stopMove(200);
    arcAngle(90, 0, 80, 50, 90);
    arcEnc(-20, 20, 20, 15, 20);
    stopMove(200);

    arcAngle(-25, -25, 80, 20, 90);
    changePosGrabberD(60, grabberD.openBackwardMax);
    stopMove(550);

    setDefaultLine();
    lineFollowEncoder(25, 25, 20, 180);
    changePosGrabberD(60, grabberD.openForwardMin);
    arcEnc(-20, 20, 20, 20, 40);
    stopMove(100);
    arcEnc(20, -20, 20, 20, 40);
    stopMove(100);
    changePosGrabberD(80, grabberD.closeBoth);
    stopMove(550);
    changePosGrabberC(100, grabberC.maxUp);
}

void getTwoPairsFromLeft(){
    arcEnc(20, -20, 40, 20, 30);
    stopMove(200);

    arcAngle(40, 0, 80, 40, 90);
    arcAngle(-70, 20, 80, 40, 90);
    arcEnc(-20, 20, 40, 20, 185);
    changePosGrabberD(100, grabberD.openForwardMax);
    stopMove(200);

    arcAngle(40, 0, 80, 40, 80);
    arcAngle(0, -40, 80, 40, 80);
    stopMove(200);
    arcEnc(-20, 20, 50, 20, 190);
    changePosGrabberD(100, grabberD.closeBoth);
    stopMove(200);

    changePosGrabberC(80, grabberC.maxUp);
    arcAngle(0, -20, 80, 20, 50);
    arcAngle(20, 0, 80, 20, 50);
    stopMove(200);
}

void getTwoPairsFromRight(){
    arcEnc(20, -20, 40, 20, 30);
    stopMove(200);

    arcAngle(0, -40, 80, 40, 90);
    arcAngle(-20, 80, 80, 40, 90);
    arcEnc(-20, 20, 40, 20, 185);
    changePosGrabberD(100, grabberD.openForwardMax);
    stopMove(200);

    arcAngle(0, -40, 80, 20, 84);
    arcAngle(40, 0, 80, 20, 84);
    stopMove(200);
    arcEnc(-20, 20, 50, 20, 190);
    changePosGrabberD(100, grabberD.closeBoth);
    stopMove(200);

    changePosGrabberC(80, grabberC.maxUp);
    arcAngle(20, 0, 80, 20, 60);
    arcAngle(0, -20, 80, 20, 60);
    stopMove(200);
}

void start(){
    readColors(encoders_markers, markers, 2, &CDSensor3);
    arcEnc(-40, 40, 40, 40, 150);
    setDefaultLine();
    lineFollowEncoder(40, 70, 70, 270);
    arcEnc(-70, 70, 70, 20, 270);
    stopMove(100);

    arcEnc(30, -30, 100, 30, 65);
    stopMove(100);
    arcAngle(0, -40, -100, -40, 50);
    stopMove(100);
    arcAngle(-40, 0, -100, -40, 40);
    arcEnc(-30, 30, 100, 20, 150);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    arcAngle(-5.25, 20, 100, 20, 180);
    arcEnc(-20, 20, 100, 15, 60);
    changePosGrabberC(100, grabberC.maxUp);
    stopMove(300);
    arcEnc(20, -20, 100, 15, 60);
    arcAngle(0, -70, -100, -70, 90);
    arcEnc(70, -70, 100, 70, 240);
    arcAngle(0, -70, -100, -40, 90);
    stopMove(100);
    lineFollowEncoder(20, 100, 100, 300);
    lineFollowCross(MTVarsB.targetV, 70, 1);
    lineFollowEncoder(70, 70, 20, 400);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    stopMove(300);
    arcEnc(30, -30, 100, 20, 400 - g_distBetweenSensorsAndWheelBase);
    stopMove(100);
    arcAngle(20, 20, 100, 20, 90);
    stopMove(100);
    lineFollowEncoder(20, 100, 20, 600);
    stopMove(150);
    int encElements[3] = {130, 200, 250};
    readColors(encElements, elements, 3, &CDSensor3, 1);
    arcAngle(-20, -20, -100, -20, 90);
    stopMove(150);
    arcAngle(20, 20, 100, 20, 90);
    setDefaultLineGreyCross();
    lineFollowCross(20, 20, 1);
    stopMove(200);
    changePosGrabberC(60, grabberC.maxDown);
    arcEnc(20, -20, 80, 20, 290);
    
    elements[3] = 14 - elements[0] - elements[1] - elements[2];

    short markersIndexies[2] = {0, 0};
    bool firstFound = false;
    bool secondFound = false;

    for(short index = 0; index < 4; index++){
        if (markers[0] == elements[index] && !firstFound){
            markersIndexies[0] = index;
            firstFound = true;
        }
        else if (markers[1] == elements[index] && !secondFound){
            markersIndexies[1] = index;
            secondFound = true;
        }
    }

    eraseDisplay();
    displayCenteredTextLine(1, "indexies_need: %d %d", markersIndexies[0], markersIndexies[1]);
    displayCenteredTextLine(4, "elements: %d %d %d %d", elements[0], elements[1], elements[2], elements[3]);
    displayCenteredTextLine(8, "markers: %d %d", markers[0], markers[1]);

    if ((markersIndexies[0] == 0 && markersIndexies[1] == 2) || (markersIndexies[1] == 0 && markersIndexies[0] == 2)){
        getOneByOneFromLeft();
    }
    else if ((markersIndexies[0] == 1 && markersIndexies[1] == 3) || (markersIndexies[1] == 1 && markersIndexies[0] == 3)){
        getOneByOneFromRight();
    }
    else if ((markersIndexies[0] == 0 && markersIndexies[1] == 1) || (markersIndexies[1] == 0 && markersIndexies[0] == 1)){
        getTwoPairsFromLeft();
    }
    else if ((markersIndexies[0] == 2 && markersIndexies[1] == 3) || (markersIndexies[1] == 2 && markersIndexies[0] == 3)){
        getTwoPairsFromRight();
    }
    else if ((markersIndexies[0] == 1 && markersIndexies[1] == 2) || (markersIndexies[1] == 1 && markersIndexies[0] == 2)){
        getCenterThenBorderElements();
    }
    else if ((markersIndexies[0] == 0 && markersIndexies[1] == 3) || (markersIndexies[1] == 0 && markersIndexies[0] == 3)){
        getBorderThenCenterElements();
    }

    arcAngle(20, 20, 100, 20, 180);
    lineFollowCross(20, 60, 1);
    changePosGrabberC(100, grabberC.upForDrop);
    lineFollowEncoder(60, 80, 15, 430);
    stopMove(100);
    changePosGrabberD(30, grabberD.dropFirstTwo);
    stopMove(200);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    arcEnc(-20, 20, 60, 14, 185);
    changePosGrabberC(100, grabberC.maxUp);
    stopMove(350);
    arcAngle(20, 20, 80, 20, 90);
    stopMove(100);
    arcEnc(-20, 20, 80, 40, 560);
    arcAngle(-17, 40, 80, 20, 90);
    setDefaultLine();
    lineFollowCross(20, 40, 1);
    lineFollowEncoder(40, 40, 20, g_distBetweenSensorsAndWheelBase);
    stopMove(200);
    arcAngle(-20, -20, 70, 20, 90);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    lineFollowEncoder(20, 40, 20, 250);
    arcEnc(20, -20, 40, 20, 250);
    changePosGrabberC(100, grabberC.maxUp);
    arcAngle(20, 20, 70, 20, 90);
    setDefaultLineGreyCross();
    lineFollowEncoder(20, 80, 80, 450);
    lineFollowCross(80, 15, 1);

    arcAngle(40, 0, 90, 40, 59);
    changePosGrabberC(100, grabberC.maxDown);
    arcAngle(0, -40, 90, 40, 59);

    arcEnc(-20, 20, 80, 15, 140);
    changePosGrabberD(100, grabberD.closeBoth);
    stopMove(100);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);

    arcEnc(-20, 20, 80, 15, 80);
    stopMove(100);
    arcAngle(0, -40, 90, 40, 59);
    arcAngle(40, 0, 90, 40, 59);

    arcAngle(20, 20, 80, 20, 180);
    setDefaultLine();
    lineFollowEncoder(20, 60, 60, 250);
    lineFollowCross(60, 20, 1);
    lineFollowEncoder(80, 80, 20, g_distBetweenSensorsAndWheelBase);
    arcAngle(-20, -20, 80, 20, 90);
    lineFollowEncoder(20, 40, 20, 280);
    stopMove(100);
    changePosGrabberC(100, grabberC.maxUp);


    /* Написать отъезд в зону выгрузки
    stopMove(350);
    arcEnc(20, -20, 80, 15, 1200);
    stopMove(5000);

    arcAngle(0, 60, 90, 60, 90);
    lineFollowEncoder(40, 80, 40, 580);
    arcEnc(40, -40, 40, 40, 300);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    stopMove(200);
    arcEnc(20, -20, 40, 20, 50);
    changePosGrabberC(60, grabberC.upForDrop);
    stopMove(200);
    changePosGrabberD(100, grabberD.openBackwardMax);
    sleep(500);
    changePosGrabberC(100, grabberC.maxUp);
    setDefaultLineWhiteCross();
    arcEnc(20, -20, 80, 20, 200);
    arcAngle(-20, -20, 80, 25, 180);
    lineFollowEncoder(20, 80, 80, 400);
    arcEnc(-80, 80, 80, 13, 400);
    */
}


task main(){
    initAll();
    stopMove(100);
    float now = getBatteryVoltage();
    now = getBatteryVoltage();
    if (now < 7.8){
        playSound(soundException);
    }

    unsigned long varPgmTime = nPgmTime;

    start();
    eraseDisplay();
    displayCenteredTextLine(2, "%d", nPgmTime - varPgmTime);

    stopMove(20000);
    fileClose(fileHandle);

}
