#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ,               sensorI2CCustom9V)
#pragma config(Sensor, S4,     ,               sensorI2CCustom9V)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Medium, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define READ
#include "include/includes.h"

short markers[2] = {0, 0};
short elements[4] = {0, 0, 0, 0};
int encoders_markers[2] = {390, 470};
int encoders_elements[4] = {603, 733, 863, 993};

void getCenterThenBorderElements(){
    setDefaultLine();
    lineFollowEncoder(30, 80, 30, 235);
    arcEnc(-30, 30, 30, 30, 15);
    changePosGrabberD(100, grabberD.openForwardMax);
    stopMove(300);
    arcEnc(30, -30, 50, 20, 150);
    stopMove(200);

    arcAngle(30, 30, 70, 20, 20);
    stopMove(200);
    arcEnc(-30, 30, 40, 20, 105);
    changePosGrabberD(100, grabberD.closeBoth);
    stopMove(300);
    arcEnc(30, -30, 40, 20, 185);
    stopMove(200);
    arcAngle(-30, -30, -70, -20, 33.5);
    stopMove(200);
    changePosGrabberD(80, grabberD.openForwardMax);
    arcEnc(-30, 30, 40, 20, 190);
    changePosGrabberD(100, grabberD.closeBoth);
    stopMove(300);
    arcEnc(30, -30, 40, 20, 300);
    stopMove(200);
    changePosGrabberC(80, grabberC.maxUp);
    arcAngle(-30, -30, -100, -30, 164);
    stopMove(0);
}

void getBorderThenCenterElements(){
    setDefaultLine();
    arcAngle(40, 0, 100, 40, 40);
    arcEnc(-30, 30, 40, 40, 165);
    arcEnc(-75, 41, 50, 35, 175);
    arcEnc(-35, 35, 35, 20, 65);
    changePosGrabberD(80, grabberD.openForwardMax);
    stopMove(200);

    arcAngle(50, 0, 100, 40, 90);
    arcAngle(0, -50, -100, -40, 112);
    changePosGrabberD(80, grabberD.openBackwardMin);
    stopMove(200);

    arcEnc(-30, 30, 40, 20, 245);
    changePosGrabberD(80, grabberD.openForwardMax);
    stopMove(200);

    arcEnc(0, -30, -100, -40, 420);
    arcEnc(30, 0, 100, 40, 420);
    stopMove(100);
    lineFollowEncoder(20, 60, 20, 220);
    changePosGrabberD(80, grabberD.closeBoth);
    stopMove(250);
    arcAngle(30, 30, 100, 30, 180);
    changePosGrabberC(80, grabberC.maxUp);
    stopMove(0);
}

void getOneByOneFromLeft(){
    setDefaultLine();
    arcEnc(20, -20, 20, 20, 30);
    stopMove(100);
    arcAngle(20, 20, 100, 20, 90);
    stopMove(200);
    arcAngle(-80, 19, -80, -20, 90);
    stopMove(200);
    arcEnc(-20, 20, 20, 20, 45);
    changePosGrabberD(80, grabberD.openForwardMax);
    stopMove(200);
    arcEnc(20, -20, 20, 20, 15);
    stopMove(100);
    arcAngle(80, -15, 80, 20, 90);
    stopMove(100);
    arcEnc(20, -20, 50, 20, 160);
    stopMove(100);
    arcAngle(-20, -20, 100, 20, 90);
    stopMove(100);
    arcEnc(-20, 20, 100, 15, 160);
    changePosGrabberD(80, grabberD.closeBoth);
    stopMove(200);
    arcAngle(0, -40, -100, -30, 90);
    arcEnc(-30, 30, 40, 20, 30);
    stopMove(200);

    arcAngle(25, 25, 80, 25, 90);
    changePosGrabberD(100, grabberD.openBackwardMax);
    stopMove(400);
    setDefaultLine();
    lineFollowEncoder(25, 25, 20, 165);
    changePosGrabberD(80, grabberD.openForwardMin);
    stopMove(400);
    arcEnc(20, -20, 40, 20, 20);
    changePosGrabberD(100, grabberD.closeBoth);
    stopMove(400);
    changePosGrabberC(100, grabberC.maxUp);
    arcAngle(30, 30, 100, 30, 180);
    stopMove(0);
}

void getOneByOneFromRight(){
    setDefaultLine();
    arcEnc(20, -20, 20, 20, 30);
    stopMove(100);
    arcAngle(-20, -20, -100, -20, 90);
    stopMove(200);
    arcAngle(-16, 80, 80, 20, 90);
    stopMove(200);
    arcEnc(-20, 20, 20, 20, 70);
    changePosGrabberD(80, grabberD.openForwardMax);
    stopMove(200);
    arcEnc(20, -20, 20, 20, 30);
    stopMove(100);
    arcAngle(15, -80, -80, -20, 90);
    stopMove(100);
    arcEnc(20, -20, 50, 20, 175);
    stopMove(100);
    arcAngle(20, 20, -100, -20, 90);
    stopMove(100);
    arcEnc(-20, 20, 100, 15, 185);
    changePosGrabberD(80, grabberD.closeBoth);
    stopMove(200);
    arcAngle(40, 0, 100, 30, 90);
    arcEnc(-30, 30, -30, -30, 15);
    stopMove(200);

    arcAngle(-25, -25, -80, -25, 90);
    changePosGrabberD(100, grabberD.openBackwardMax);
    stopMove(400);
    setDefaultLine();
    lineFollowEncoder(25, 25, 20, 170);
    changePosGrabberD(80, grabberD.openForwardMin);
    stopMove(400);
    arcEnc(20, -20, 40, 20, 20);
    changePosGrabberD(100, grabberD.closeBoth);
    stopMove(400);
    changePosGrabberC(100, grabberC.maxUp);
    arcAngle(30, 30, 100, 30, 180);
    stopMove(0);
}

void getTwoPairsFromLeft(){
    arcEnc(20, -20, 40, 20, 30);
    stopMove(200);

    arcAngle(40, 0, 80, 40, 90);
    stopMove(200);
    arcAngle(-70, 20, 80, 40, 90);
    arcEnc(-20, 20, 40, 20, 185);
    changePosGrabberD(100, grabberD.openForwardMax);
    stopMove(300);

    arcAngle(40, 0, 80, 40, 80);
    arcAngle(0, -40, 80, 40, 80);
    stopMove(200);
    arcEnc(-20, 20, 50, 20, 190);
    changePosGrabberD(100, grabberD.closeBoth);
    stopMove(300);

    changePosGrabberC(80, grabberC.maxUp);
    arcAngle(-23, -50, -100, -50, 180);
    stopMove(0);
}

void getTwoPairsFromRight(){
    arcEnc(20, -20, 40, 20, 30);
    stopMove(200);

    arcAngle(0, -40, 80, 40, 90);
    stopMove(200);
    arcAngle(-20, 80, 80, 40, 90);
    arcEnc(-20, 20, 40, 20, 210);
    changePosGrabberD(100, grabberD.openForwardMax);
    stopMove(300);

    arcAngle(0, -40, -80, -20, 84);
    arcAngle(40, 0, 80, 20, 84);
    stopMove(200);
    arcEnc(-20, 20, 50, 20, 200);
    changePosGrabberD(100, grabberD.closeBoth);
    stopMove(300);

    changePosGrabberC(100, grabberC.maxUp);
    arcAngle(50, 17, 100, 50, 180);
    stopMove(0);
}

void start(){
    readColors(encoders_markers, markers, 2, &CDSensor3);
    arcEnc(-40, 40, 50, 50, 150);
    setDefaultLine();
    lineFollowEncoder(50, 70, 70, 270);
    arcEnc(-70, 70, 70, 20, 270);
    stopMove(100);

    arcEnc(30, -30, 100, 30, 65);
    stopMove(100);
    arcAngle(0, -40, -100, -40, 50);
    stopMove(100);
    arcAngle(-40, 0, -100, -40, 40);
    arcEnc(-30, 30, 100, 20, 150);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    arcAngle(-5.25, 20, 100, 20, 180);
    arcEnc(-20, 20, 100, 50, 60);
    changePosGrabberC(100, grabberC.maxUp);
    arcAngle(0, 50, 100, 50, 130);
    arcEnc(-50, 50, 100, 50, 300);
    arcAngle(0, 50, 100, 50, 50);
    lineFollowCross(50, 100, 1)
    lineFollowEncoder(100, 100, 20, 400);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    stopMove(300);
    arcEnc(30, -30, 100, 20, 400 - g_distBetweenSensorsAndWheelBase);
    stopMove(100);
    arcAngle(20, 20, 100, 20, 90);
    stopMove(100);
    lineFollowEncoder(20, 100, 20, 600);
    int encElements[3] = {110, 165, 240};
    readColors(encElements, elements, 3, &CDSensor3, 1);
    arcAngle(-20, -20, -100, -20, 90);
    stopMove(100);
    changePosGrabberC(100, grabberC.upForShipPush);
    arcAngle(20, 20, 100, 20, 90);
    setDefaultLineGreyCross();
    lineFollowCross(20, 20, 1);
    stopMove(200);
    changePosGrabberC(100, grabberC.maxDown);
    arcEnc(20, -20, 80, 20, 290);
    stopMove(200);
    elements[3] = 14 - elements[0] - elements[1] - elements[2];

    short markersIndexies[2] = {0, 0};
    bool firstFound = false;
    bool secondFound = false;

    for(short index = 0; index < 4; index++){
        if (markers[0] == elements[index] && !firstFound){
            markersIndexies[0] = index;
            firstFound = true;
        }
        else if (markers[1] == elements[index] && !secondFound){
            markersIndexies[1] = index;
            secondFound = true;
        }
    }

    // eraseDisplay();
    // displayCenteredTextLine(1, "indexies_need: %d %d", markersIndexies[0], markersIndexies[1]);
    // displayCenteredTextLine(4, "elements: %d %d %d %d", elements[0], elements[1], elements[2], elements[3]);
    // displayCenteredTextLine(8, "markers: %d %d", markers[0], markers[1]);

    if ((markersIndexies[0] == 0 && markersIndexies[1] == 2) || (markersIndexies[1] == 0 && markersIndexies[0] == 2)){
        getOneByOneFromLeft();
    }
    else if ((markersIndexies[0] == 1 && markersIndexies[1] == 3) || (markersIndexies[1] == 1 && markersIndexies[0] == 3)){
        getOneByOneFromRight();
    }
    else if ((markersIndexies[0] == 0 && markersIndexies[1] == 1) || (markersIndexies[1] == 0 && markersIndexies[0] == 1)){
        getTwoPairsFromLeft();
    }
    else if ((markersIndexies[0] == 2 && markersIndexies[1] == 3) || (markersIndexies[1] == 2 && markersIndexies[0] == 3)){
        getTwoPairsFromRight();
    }
    else if ((markersIndexies[0] == 1 && markersIndexies[1] == 2) || (markersIndexies[1] == 1 && markersIndexies[0] == 2)){
        getCenterThenBorderElements();
    }
    else if ((markersIndexies[0] == 0 && markersIndexies[1] == 3) || (markersIndexies[1] == 0 && markersIndexies[0] == 3)){
        getBorderThenCenterElements();
    }
    setDefaultLine();
    lineFollowCross(40, 80, 1);
    changePosGrabberC(100, grabberC.upForDrop);
    lineFollowEncoder(80, 80, 20, 430);
    stopMove(100);
    changePosGrabberD(30, grabberD.dropFirstTwo);
    stopMove(200);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    arcEnc(-20, 20, 60, 14, 185);
    changePosGrabberC(100, grabberC.maxUp);
    stopMove(350);
    arcAngle(20, 20, 80, 20, 90);
    stopMove(100);
    arcEnc(-20, 20, 80, 40, 560);
    arcAngle(-17, 40, 80, 20, 90);
    setDefaultLine();
    lineFollowCross(20, 40, 1);
    lineFollowEncoder(40, 40, 20, g_distBetweenSensorsAndWheelBase);
    stopMove(200);
    arcAngle(-20, -20, 70, 20, 90);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    lineFollowEncoder(20, 40, 20, 250);
    arcEnc(20, -20, 40, 20, 250);
    changePosGrabberC(100, grabberC.maxUp);
    arcAngle(20, 20, 70, 20, 90);
    changePosGrabberC(100, grabberC.maxDown);
    setDefaultLine();
    lineFollowEncoder(20, 100, 40, 280);
    arcEnc(-40, 20, -100, -40, 160);
    arcEnc(-40, 40, -100, -40, 170);
    changePosGrabberD(100, grabberD.closeBoth);
    stopMove(300);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    arcEnc(-30, -50, -100, -50, 460);

    setDefaultLine();
    lineFollowEncoder(40, 100, 100, 250);
    lineFollowCross(100, 40, 1);
    lineFollowEncoder(40, 40, 20, g_distBetweenSensorsAndWheelBase);
    arcAngle(-20, -20, 80, 20, 90);
    lineFollowEncoder(20, 40, 30, 300);
    changePosGrabberC(100, grabberC.maxUp);
    stopMove(400);
    arcAngle(40, 40, 80, 30, 180);
    lineFollowEncoder(70, 100, 100, 1200);
    lineFollowCross(100, 50, 1);
    stopMove(100);
    arcEnc(0, -50, -100, -50, 200);
    arcEnc(-50, 50, 100, 50, 100);
    arcEnc(-50, 0, -100, -50, 200);
    lineFollowEncoder(50, 50, 50, 400);
    stopMove(200);
    arcEnc(40, -40, 100, 40, 100);
    changePosGrabberC(100, grabberC.upForDrop);
    arcEnc(40, -40, 100, 30, 245);
    stopMove(400);
    changePosGrabberD(700, grabberD.openBackwardMax);
    stopMove(500);
    arcEnc(40, -40, 100, 40, 300);
    changePosGrabberC(100, grabberC.maxUp);
    arcAngle(40, 40, 100, 40, 180);
    lineFollowEncoder(40, 60, 60, 300);
    arcEnc(-60, 60, 60, 20, 300);
}


task main(){
    initAll();
    stopMove(100);
    float now = getBatteryVoltage();
    now = getBatteryVoltage();
    if (now < 7.8){
        playSound(soundException);
    }

    unsigned long varPgmTime = nPgmTime;

    start();
    eraseDisplay();
    displayCenteredTextLine(2, "%d", nPgmTime - varPgmTime);

    stopMove(20000);
    fileClose(fileHandle);
}
