#pragma config(Sensor, S1,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2,     ,               sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ,               sensorI2CCustom9V)
#pragma config(Sensor, S4,     ,               sensorI2CCustom9V)
#pragma config(Motor,  motorA,          leftMotor,     tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor,  motorB,          rightMotor,    tmotorEV3_Medium, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define READ
#include "include/includes.h"

int markers[2] = {0, 0};

task main(){
    initAll();
    setLeftSensorBlackLineBlackStop(1, 1);
    fileClose(fileHandle);


	{
		int encoders[2] = {390, 480};
    	readColors(encoders, 2, &CDSensor3);
	}



    arcEnc(-40, 40, 50, 50, 200);
    setLeftSensorBlackLineBlackStop(1, 1);
    lineFollowCross(50, 50, 1);
    changePosGrabberC(100, grabberC.maxUpWithoutShip);
    arcEnc(-50, 50, 100, 15, 250);
    stopMove(200);


    markers[0] = readingRes[0];
    markers[1] = readingRes[1];

    arcAngle(-20, -20, -70, -20, 110);
    arcAngle(20, 20, 70, 20, 105);
    arcEnc(-20, 20, 70, 20, 300);
    changePosGrabberC(100, grabberC.maxUp);
    arcEnc(-20, 20, 70, 15, 60);
    arcAngle(0, -20, -70, -30, 25);
    arcAngle(-30, -30, -70, -20, 60);
    arcEnc(-20, 40, 100, 30, 210);
    arcEnc(-40, 20, -100, -20, 210);

	{
		int encoders[4] = {250, 390, 530, 670};
    	readColors(encoders, 4, &CDSensor3);
	}
	changePosGrabberC(80, grabberC.maxUpWithoutShip);
    arcEnc(-20, 20, 100, 20, 830);
    arcEnc(20, -20, 100, 50, 100);
    arcAngle(50, 0, 100, 40, 90);
    //stopMove(200);
    //arcEnc(-20, 20, 20, 20, 140);
    //stopMove(200);
    //arcEnc(-20, 20, 20, 20, 140);
    //stopMove(200);
    //arcEnc(-20, 20, 20, 20, 140);
	stopMove(2150);

}
