#pragma config(Sensor, S1, sensorLeft, sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2, sensorRight, sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ,               sensorI2CCustom9V)
#pragma config(Sensor, S4,     ,               sensorI2CCustom9V)
#pragma config(Motor, motorA, motorLeftWheel, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorB, motorRightWheel, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorC, motorLeftGrabber, tmotorEV3_Medium, openLoop,encoder)
#pragma config(Motor, motorD, motorRightGrabber, tmotorEV3_Medium, openLoop,encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

#define WRITE
#include "../include/includes.h"

task main (){
	initAll();
    setMotorBrakeMode(motorA, motorCoast);
    setMotorBrakeMode(motorB, motorCoast);
    setMotorBrakeMode(motorD, motorCoast);
    setMotorBrakeMode(motorC, motorCoast);
    long maxR, maxG, maxB;
    long minR, minG, minB;

    tCDValues *mass[4];
    mass[0] = &CDSensor1;
    mass[1] = &CDSensor2;
    mass[2] = &CDSensor3;
    mass[3] = &CDSensor4;

    for(short j = 0; j < 4; j++){
        maxR = 0;
        maxG = 0;
        maxB = 0;
        minR = 1000;
        minG = 1000;
        minB = 1000;
        while (!getButtonPress('C')) {
            getCDValues(mass[j]);
            minR = min2(minR, mass[j]->rawRed);
            minG = min2(minG, mass[j]->rawGreen);
            minB = min2(minB, mass[j]->rawBlue);
            maxR = max2(maxR, mass[j]->rawRed);
            maxG = max2(maxG, mass[j]->rawGreen);
            maxB = max2(maxB, mass[j]->rawBlue);
            displayCenteredTextLine(1, "RGB_min: %d %d %d %d", minR, minG, minB, j);
            displayCenteredTextLine(3, "RGB_max: %d %d %d %d", maxR, maxG, maxB, j);
            sleep(250);
            eraseDisplay();
        }
        writeRGB(maxR, maxG, maxB);
        writeRGB(minR, minG, minB);
        sleep(200);
        flushButtonMessages();
    }
    fileClose(fileHandle);
}
