#pragma config(Sensor, S1, sensorLeft, sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2, sensorRight, sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ,               sensorI2CCustom9V)
#pragma config(Sensor, S4,     ,               sensorI2CCustom9V)
#pragma config(Motor, motorA, motorLeftWheel, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorB, motorRightWheel, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorC, motorLeftGrabber, tmotorEV3_Medium, openLoop,encoder)
#pragma config(Motor, motorD, motorRightGrabber, tmotorEV3_Medium, openLoop,encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

#define READ
#include "../include/includes.h"

task main (){
	initAll();

    sleep(2000);
    motor[motorA] = 0;
    motor[motorB] = 0;
    motor[motorC] = 0;
    motor[motorD] = 0;

    setMotorBrakeMode(motorA, motorCoast);
    setMotorBrakeMode(motorB, motorCoast);
    setMotorBrakeMode(motorD, motorCoast);
    setMotorBrakeMode(motorC, motorCoast);
    while (!getButtonPress('C')) {
        getCDValues(CDSensor1);
        getCDValues(CDSensor2);
        getCDValues(CDSensor3);
        getCDValues(CDSensor4);

        displayCenteredTextLine(1, "HSV_1: %d %f %d", CDSensor1.hue, CDSensor1.sat, CDSensor1.val);
        displayCenteredTextLine(3, "HSV_2: %d %f %d", CDSensor2.hue, CDSensor2.sat, CDSensor2.val);
        displayCenteredTextLine(6, "HSV_3: %d %f %d", CDSensor3.hue, CDSensor3.sat, CDSensor3.val);
        displayCenteredTextLine(9, "HSV_4: %d %f %d", CDSensor4.hue, CDSensor4.sat, CDSensor4.val);

        sleep(250);
        eraseDisplay();
    }
    fileClose(fileHandle);
}
