#pragma config(Sensor, S1, sensorLeft, sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2, sensorRight, sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ,               sensorI2CCustom9V)
#pragma config(Sensor, S4,     ,               sensorI2CCustom9V)
#pragma config(Motor, motorA, motorLeftWheel, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorB, motorRightWheel, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorC, motorLeftGrabber, tmotorEV3_Medium, openLoop,encoder)
#pragma config(Motor, motorD, motorRightGrabber, tmotorEV3_Medium, openLoop,encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

#define READ
#include "../include/includes.h"

task main (){
	initAll();

    sleep(2000);
    motor[motorA] = 0;
    motor[motorB] = 0;
    motor[motorC] = 0;
    motor[motorD] = 0;

    setMotorBrakeMode(motorA, motorCoast);
    setMotorBrakeMode(motorB, motorCoast);
    setMotorBrakeMode(motorD, motorCoast);
    setMotorBrakeMode(motorC, motorCoast);

    while (!getButtonPress('C')) {
        getCDValues(CDSensor1);
        getCDValues(CDSensor2);
        getCDValues(CDSensor3);
        getCDValues(CDSensor4);

        displayCenteredTextLine(1, "RGBC_1: %d %d %d %d", CDSensor1.normRed, CDSensor1.normGreen, CDSensor1.normBlue, CDSensor1.color);
        displayCenteredTextLine(3, "RGBC_2: %d %d %d %d", CDSensor2.normRed, CDSensor2.normGreen, CDSensor2.normBlue, CDSensor2.color);
        displayCenteredTextLine(6, "RGBC_3: %d %d %d %d", CDSensor3.normRed, CDSensor3.normGreen, CDSensor3.normBlue, CDSensor3.color);
        displayCenteredTextLine(9, "RGBC_4: %d %d %d %d", CDSensor4.normRed, CDSensor4.normGreen, CDSensor4.normBlue, CDSensor4.color);

        sleep(250);
        eraseDisplay();
    }

    fileClose(fileHandle);
}
