#pragma config(Sensor, S1, sensorLeft, sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S2, sensorRight, sensorEV3_Color, modeEV3Color_RGB_Raw)
#pragma config(Sensor, S3,     ,               sensorI2CCustom9V)
#pragma config(Sensor, S4,     ,               sensorI2CCustom9V)
#pragma config(Motor, motorA, motorLeftWheel, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorB, motorRightWheel, tmotorEV3_Medium, openLoop, encoder)
#pragma config(Motor, motorC, motorLeftGrabber, tmotorEV3_Medium, openLoop,encoder)
#pragma config(Motor, motorD, motorRightGrabber, tmotorEV3_Medium, openLoop,encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard !!*//

#define READ
#include "../include/includes.h"

task main (){
	initAll();

    sleep(2000);
    motor[motorA] = 0;
    motor[motorB] = 0;
    motor[motorC] = 0;
    motor[motorD] = 0;

    setMotorBrakeMode(motorA, motorCoast);
    setMotorBrakeMode(motorB, motorCoast);
    setMotorBrakeMode(motorD, motorCoast);
    setMotorBrakeMode(motorC, motorCoast);

    offAllSensors()

    fileClose(fileHandle);
}
